In [2]:
import numpy as np

<br> **Eigen vectors of different eigen values of a symmetric matrix form an orthogonal system of vectors.**<br\>
  ***PROOF***
- Let $A \in \Re^{n \times n} $ be a symmetric matrix. ($A = A^T$). Let $( \lambda_1, v_1 ), (\lambda_2, v_2 ) $ be two eigen value - vector pairs where $\lambda_1 \neq \lambda_2 $. The eigen value equations are $Av_1 = \lambda_1 v_1 \;\;Av_2 = \lambda_2 v_2 $. Therefore $v_2^T Av_1 = \lambda_2 v_2^T v_1 $. But $v_2^T A = \lambda_2 v_2^T$. Putting this into the previous equation yields $\lambda_2 v_2^T v_1 = \lambda_1 v_2^T v_1$. Since $\lambda_1 \neq \lambda_2$ we have $v_2^T v_1 = 0 $
- The example below illustrates this 

In [3]:
a = [1,0,1,0,2,2,1,2,3]
amat = np.array(a).reshape((3,3)).T
print(amat)

[[1 0 1]
 [0 2 2]
 [1 2 3]]


In [4]:
e,v = np.linalg.eig(amat)
print('eigen values','\n',e,'\n','vectors', '\n',v)

eigen values 
 [  4.73205081e+00   1.26794919e+00  -8.04992623e-17] 
 vectors 
 [[-0.21132487 -0.78867513 -0.57735027]
 [-0.57735027  0.57735027 -0.57735027]
 [-0.78867513 -0.21132487  0.57735027]]


In [5]:
b = np.dot(np.dot(v, np.diag(e)),v.T)
print(b.round())

[[ 1. -0.  1.]
 [-0.  2.  2.]
 [ 1.  2.  3.]]


In [6]:
#Orthogonality of v
print(np.dot(v.T,v))

[[  1.00000000e+00  -2.49800181e-16  -2.22044605e-16]
 [ -2.49800181e-16   1.00000000e+00  -4.57966998e-16]
 [ -2.22044605e-16  -4.57966998e-16   1.00000000e+00]]


## Singular Value Decomposition
- $A \in \Re^{m\times n}$ 
- $A$ can be written as a product of three matrices $U,S,V$
- $U$ is an $m \times m$ orthogonal matrix
- $V$ is an $n \times n$ orthogonal matrix
- $S$ is an $m \times n$ diagnonal matrix

- $ A = USV^T $
- $AA^T = US^2 U^T$
- $A^TA = V S^2 V^T $


In [7]:
A = np.array(np.arange(1,13)).reshape((3,4))
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
S2,U = np.linalg.eig(np.dot(A,A.T))
_,V = np.linalg.eig(np.dot(A.T,A))


[  6.47032607e+02   2.96739296e+00   4.87870499e-14]


In [9]:
print(np.dot(U,U.T))

[[  1.00000000e+00   4.99600361e-16   0.00000000e+00]
 [  4.99600361e-16   1.00000000e+00  -4.44089210e-16]
 [  0.00000000e+00  -4.44089210e-16   1.00000000e+00]]


In [10]:
print(np.dot(V.T,V))

[[  1.00000000e+00  -2.77555756e-16  -1.94289029e-16  -1.05818132e-16]
 [ -2.77555756e-16   1.00000000e+00  -1.67088565e-14  -1.32255318e-14]
 [ -1.94289029e-16  -1.67088565e-14   1.00000000e+00   7.55698876e-01]
 [ -1.05818132e-16  -1.32255318e-14   7.55698876e-01   1.00000000e+00]]


In [13]:
S = np.zeros_like(A, dtype = float)
for i in range(0,S2.shape[0]):
    S[i,i] = np.sqrt(S2[i])
B = np.dot( np.dot(U,S), V.T  )
print(B)

[[  2.54368356e+01   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.72261225e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.20877907e-07   0.00000000e+00]]
[[  1.00000005   1.99999993   2.99999999   4.00000003]
 [  4.9999999    6.00000014   7.00000002   7.99999994]
 [  9.00000005   9.99999993  10.99999999  12.00000003]]


- In the above example see that V is not exactly orthogonal since $V^T V$ has element (2,3) = 0.755. This is bacause the matrix is 3x4 and hence can have only 3 singular values. Therefore the fourth column of $V$ is immaterial. You can change it with any random vector as shown below:

In [15]:
V[:,3] = np.random.randn(4)
B = np.dot( np.dot(U,S), V.T  )
print(B.round())

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]]


- We can generalize this further. If $A \in \Re^{m \times n} $ has rank $r$, then will be only $r$ non-zero singular values. This means that only $r$ columns of $U$ and $V$ are relevant. You can replace the remaining columns of both matrices by any arbitrary vectors. Still $A = USV^T$ holds. 